---

### site serving configuration ###

port: 8081
host: 0.0.0.0
safe: false

exclude:
    - LICENSE
    - README.md
    - INSTALL.md
    - Makefile
    - Dockerfile
    - vendor
    - CNAME
    - .gitignore

#plugins:
#  - jekyll-sitemap
#  - jekyll-redirect-from

source: "./docs"

# site settings
title: "CITS4407 Open Source Tools and Scripting"
description: "CITS4407 Open Source Tools and Scripting  unit @uwa"
#url: "https://arranstewart.github.io/cits4407.github.io"
repository: "arranstewart/cits4407.github.io"

# other site config
permalink: /:title
timezone: "Australia/Perth"
markdown: kramdown
#kramdown:
#  math_engine: mathjax
#  syntax_highlighter: rouge

## content structure
include:
  - "_pages"
  - "assets/css"

collections:
   pages:
     output: true
     permalink: /:path/

plugins:
  - jekyll-relative-links




